# backend-api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: "{{ .Values.backend.clientName }}-ns"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: lahcenedergham/k8s-backend-api
          ports:
            - containerPort: 8080
          env:
            - name: CLIENT_NAME
              value: "{{ .Values.backend.clientName }}"
            - name: MONGODB_URI
              value: "{{ .Values.backend.mongoDBURI }}"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: "{{ .Values.backend.clientName }}-ns"
spec:
  type: NodePort
  selector:
    app: backend-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.backend.nodePort }}

