# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: "{{ .Values.clientName }}-ns"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: lahcenedergham/k8s-frontend-app
          env:
            - name: REACT_APP_CLIENT_NAME
              value: "{{ .Values.clientName }}"
            - name: REACT_APP_BACKEND_HOST
              value: "{{ .Values.frontend.backendApiUrl }}"
            - name: REACT_APP_SUBSCRIPTION
              value: "{{ .Values.frontend.subscription }}"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: "{{ .Values.clientName }}-ns"
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
        # nodePort: {{ .Values.frontend.nodePort }}

