apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-info-app
  labels:
    app: client-info-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-info-app
  template:
    metadata:
      labels:
        app: client-info-app
    spec:
      containers:
        - name: client-info
          image: lahcenedergham/k8s-client-info-app
          ports:
            - containerPort: 5555

---

# react-app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: client-info-service
spec:
  type: NodePort
  selector:
    app: client-info-app
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
