# backend-api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-info-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-info-fastapi
  template:
    metadata:
      labels:
        app: client-info-fastapi
    spec:
      containers:
        - name: client-info-fastapi
          image: lahcenedergham/k8s-client-info-fastapi
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: client-info-fastapi-service
spec:
  type: NodePort
  selector:
    app: client-info-fastapi
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30002
