# backend-api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-info-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-info-api
  template:
    metadata:
      labels:
        app: client-info-api
    spec:
      containers:
        - name: client-info-api
          image: lahcenedergham/k8s-client-info-api
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-info-api-service
spec:
  type: NodePort
  selector:
    app: client-info-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
